package edu.uga.cs.statecapitalsquiz;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

/**
 * This class is facilitates storing and restoring job leads stored.
 */
public class CurrentQuizData {

    public static final String DEBUG_TAG = "CurrentQuiz";

    // this is a reference to our database; it is used later to run SQL commands
    private SQLiteDatabase db;
    private static SQLiteOpenHelper currentQuizDataDBHelper;
    private static final String[] allColumns = {
            CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_ID,
            CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_QUESTIONID,
            CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_SELECTEDANSWER,
    };

    public CurrentQuizData(Context context) {
        currentQuizDataDBHelper = CurrentQuizDataDBHelper.getInstance(context);
    }

    // Open the database
    public void open() {
        db = currentQuizDataDBHelper.getWritableDatabase();
        Log.d(DEBUG_TAG, "CurrentQuizData: db open");
    }

    // Close the database
    public void close() {
        if (currentQuizDataDBHelper != null) {
            currentQuizDataDBHelper.close();
            Log.d(DEBUG_TAG, "CurrentQuizData: db closed");
        }
    }
    public void clear() {
        if (currentQuizDataDBHelper != null) {
            db.delete(CurrentQuizDataDBHelper.TABLE_CURRENTQUIZDATA, null, null);
        }
    }
    public boolean isDBOpen() {
        return db.isOpen();
    }

    // Retrieve all job leads and return them as a List.
    // This is how we restore persistent objects stored as rows in the job leads table in the database.
    // For each retrieved row, we create a new QuizData (Java POJO object) instance and add it to the list.
    public List < CurrentQuiz > getCurrentQuiz() {
        ArrayList < CurrentQuiz > currentQuizData = new ArrayList < > ();
        Cursor cursor = null;
        int columnIndex;

        try {
            // Execute the select query and get the Cursor to iterate over the retrieved rows
            cursor = db.query(CurrentQuizDataDBHelper.TABLE_CURRENTQUIZDATA, allColumns,
                    null, null, null, null, null);

            // collect all job leads into a List
            if (cursor != null && cursor.getCount() > 0) {
                while (cursor.moveToNext()) {
                    // No need to check column count, or at least check >= 3
                    columnIndex = cursor.getColumnIndex(CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_ID);
                    long id = cursor.getLong(columnIndex);
                    columnIndex = cursor.getColumnIndex(CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_QUESTIONID);
                    long questionId = cursor.getLong(columnIndex);
                    columnIndex = cursor.getColumnIndex(CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_SELECTEDANSWER);
                    int selectedAnswer = cursor.getInt(columnIndex);

                    CurrentQuiz currentQuiz = new CurrentQuiz(questionId, selectedAnswer);
                    currentQuiz.setId(id);
                    currentQuizData.add(currentQuiz);
                    Log.d(DEBUG_TAG, "Retrieved QuizData: " + currentQuiz);
                }
            }
        } catch (Exception e) {
            Log.d(DEBUG_TAG, "Exception caught: " + e);
        } finally {
            // we should close the cursor
            if (cursor != null) {
                cursor.close();
            }
        }
        return currentQuizData;
    }

    // Store a new job lead in the database.
    public CurrentQuiz storeQuizData(CurrentQuiz currentQuiz) {

        // Prepare the values for all of the necessary columns in the table
        // and set their values to the variables of the QuizData argument.
        // This is how we are providing persistence to a QuizData (Java object) instance
        // by storing it as a new row in the database table representing job leads.
        ContentValues values = new ContentValues();
        values.put(CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_QUESTIONID, currentQuiz.getQuestionid());
        values.put(CurrentQuizDataDBHelper.CURRENTQUIZDATA_COLUMN_SELECTEDANSWER, currentQuiz.getSelectedAnswer());
        // Insert the new row into the database table;
        // The id (primary key) is automatically generated by the database system
        // and returned as from the insert method call.
        long id = db.insert(CurrentQuizDataDBHelper.TABLE_CURRENTQUIZDATA, null, values);
        // store the id (the primary key) in the QuizData instance, as it is now persistent
        currentQuiz.setId(id);

        Log.d(DEBUG_TAG, "Stored current quiz with id: " + String.valueOf(currentQuiz.getId()));

        return currentQuiz;
    }

}